<a href="https://colab.research.google.com/github/Hamza7232/Numpy-Pandas-Matplotlib-Notes/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.ones((3, 5), dtype=float)     # Create a 3x5 floating-point array filled with 1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)      # arrange is exclusive of end value

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5)       # linspace includes end value

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[8, 7, 4],
       [9, 4, 5],
       [3, 3, 6]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(10, size=6) # One-dimensional array

array([2, 4, 6, 7, 5, 5])

In [ ]:
np.random.randint(10, size=(3, 4, 5))

array([[[2, 4, 8, 8, 5],
        [1, 2, 0, 5, 1],
        [7, 0, 4, 6, 5],
        [4, 6, 1, 3, 3]],

       [[5, 4, 4, 6, 3],
        [0, 5, 0, 7, 4],
        [9, 9, 9, 1, 4],
        [5, 3, 4, 1, 2]],

       [[0, 2, 7, 9, 1],
        [2, 7, 0, 8, 5],
        [8, 1, 5, 4, 6],
        [7, 6, 6, 9, 1]]])

In [ ]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
#Each array has attributes ndim (the number of dimensions), shape (the size of each
#dimension), and size (the total number of elements in an array):
print("x3 ndim: ", x3.ndim)   
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print("dtype:", x3.dtype)   #prints data type
print(x3.itemsize) #size of each element in bytes
print(x3.nbytes) #number of bytes occupied by whole array (size times itemsize)

dtype: int64
8
480


In [ ]:
import numpy as np
x = np.arange(10)
x[5:10]

array([5, 6, 7, 8, 9])

In [ ]:
x2
x2[:2, :3] # two rows, three columns
print(x2[:, 0]) # first column of x2
print(x2[1,:]) # second row of x2

[3 7 1]
[7 6 8 8]


In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])  # concatenates both array

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
import numpy as np
x=np.arange(4)
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])